---
driver:
  name: docker
  use_sudo: false
  port_forward:
    - 9200:9200

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-jessie
    run_list:
      - recipe[elastalert_test::elasticsearch]

suites:
  - name: default
    run_list:
      - recipe[elastalert]
      - recipe[elastalert_test::add_rule]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
