driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[elastalert]
      - recipe[elastalert_test::add_rule]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
