---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: debian-jessie
    #driver_config:
      # provision_command: apt-get update

suites:
  - name: default
    run_list:
      - recipe[elasticsearch]
      - recipe[elastalert]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
