name 'elastalert'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures elastalert'
long_description 'Installs/Configures elastalert'
version '0.1.0'

depends 'poise-python', '~> 1.5.1'
depends 'git', '~> 5.0.1'
depends 'managed_directory', '~> 0.2.1'
depends 'supervisor', '~> 0.4.12'
