name 'elastalert'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures elastalert'
long_description 'Installs/Configures elastalert'
version '0.1.0'

depends 'poise-python'
depends 'git'
depends 'elasticsearch', '~> 2.4'
